name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: [self-hosted]

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Change permissions
      run: echo ${{ secrets.PASSWORD }} | sudo -S chmod -R 777 /home/runner/actions-runner/dndmt/dnd-charactersheet/dnd-charactersheet
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Set up environment variables
      run: |
        if [ ! -f .env ]; the
          touch .env
        fi
        echo "NEXT_PUBLIC_APPWRITE_ENDPOINT=${{secrets.NEXT_PUBLIC_APPWRITE_ENDPOINT}}" >> .env
        echo "NEXT_PUBLIC_COLLECTION_SPELL_ID=${{secrets.NEXT_PUBLIC_COLLECTION_SPELL_ID}}" >> .env
        echo "NEXT_PUBLIC_DATABASE_ID=${{secrets.NEXT_PUBLIC_DATABASE_ID}}" >> .env
        echo "NEXT_PUBLIC_PROJECT_ID=${{secrets.NEXT_PUBLIC_PROJECT_ID}}" >> .env
        echo "NEXT_PUBLIC_SHEET_COLLECTION_ID=${{secrets.NEXT_PUBLIC_SHEET_COLLECTION_ID}}" >> .env
        echo "NEXT_PUBLIC_BUCKET_ID=${{secrets.NEXT_PUBLIC_BUCKET_ID}}" >> .env
    - name: Run npm commands with sudo
      run: |
        echo ${{ secrets.PASSWORD }} | sudo -S npm ci
        echo ${{ secrets.PASSWORD }} | sudo -S npm run build
        echo ${{ secrets.PASSWORD }} | sudo -S pm2 restart dndmt --update-env
            

