name: Deployment Workflow

# Trigger this workflow on pushes to the specified branch
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env: 
      NEXT_PUBLIC_APPWRITE_ENDPOINT: ${{secrets.NEXT_PUBLIC_APPWRITE_ENDPOINT}}
      NEXT_PUBLIC_COLLECTION_SPELL_ID: ${{secrets.NEXT_PUBLIC_COLLECTION_SPELL_ID}}
      NEXT_PUBLIC_DATABASE_ID: ${{secrets.NEXT_PUBLIC_DATABASE_ID}}
      NEXT_PUBLIC_PROJECT_ID: ${{secrets.NEXT_PUBLIC_PROJECT_ID}}
      NEXT_PUBLIC_SHEET_COLLECTION_ID: ${{secrets.NEXT_PUBLIC_SHEET_COLLECTION_ID}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
        
      - name: Build Next.js app
        run: npm run build

      - name: SSH Deploy
        # Use the 'appleboy/ssh-action' action for SSH deployment
        uses: appleboy/ssh-action@master
        with:
          host: "lostcausenetwork.com" # Your server's IP address
          username: ${{ secrets.USERNAME }} # Your server's username
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Your server's SSH private key
          script: |
            cd /var/www/dnd-charactersheet # Specify the path to your app directory on the server
            git pull
            npm install
            npm run build
            pm2 restart dnd-charactersheet # Replace with your PM2 service name
