# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - name: create env file
      run: |
        touch .env
        echo NEXT_PUBLIC_API_KEY=${{ secrets.NEXT_PUBLIC_API_KEY }} >> .env
        echo NEXT_PUBLIC_APPWRITE_ENDPOINT=${{ secrets.NEXT_PUBLIC_APPWRITE_ENDPOINT }} >> .env
        echo NEXT_PUBLIC_COLLECTION_SPELL_ID=${{ secrets.NNEXT_PUBLIC_COLLECTION_SPELL_ID }} >> .env
        echo NEXT_PUBLIC_DATABASE_ID=${{ secrets.NEXT_PUBLIC_DATABASE_ID }} >> .env
        echo NEXT_PUBLIC_PROJECT_ID=${{ secrets.NEXT_PUBLIC_PROJECT_ID }} >> .env

    - run: npm run build --if-present
    - name: Start PM2 instance
      run: |
        sudo pm2 start npm --name "dnd-charactersheet" -- start
        sudo pm2 save
